import { Footer } from './components/Footer/Footer'
import { Header } from './components/Header/Header'
import './globals.scss'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <div className='container content'>
          <div className={inter.className}>{children}</div>
        </div>
        <Footer />
      </body>
    </html>
  )
}
